site_name: MetatoCome Documentation
site_description: MetatoCome, Workflow, Hyper Automation
site_url: https://cnshsliu.github.io/mtcdocs/
site_author: Lucas Kehong Liu
copyright: Copyright Lucas-Kehong-Liu, 2003-2022
use_directory_urls: false
theme:
  name: material
  logo: assets/logo.png
  favicon: 'assets/favicon.ico'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83  #s
  features:
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh_CN:
          name: 中文
      nav_translations:
        zh_CN:
          Topic1: Sujet1
          Topic2: Sujet2
plugins:
  - search:
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        default:
          name: Default (en)
          build: true
        en:
          name: English
          build: true
          site_name: "MetatoCome Documentation"
        zh_CN:
          name: 中文
          build: true
          site_name: "MetatoCome文档"
      nav_translations:
        zh_CN:
          Home: 首页
          Account: 用户账户
          Register: 用户注册
          AdminReg: 组织管理
          Template: 流程规划
          Concept: 基本概念
          "Template Browser": 模板浏览
          "Design Template": 设计模板
          Designer: 设计器
          "Role Definition": 角色定义
          Process: 进程管理
          Work: 任务管理
          Setting: 设置
          For Developers: 开发者
          About: 关于我们
          "Start a process": "启动一个进程"
          "Process explorer": "进程浏览器"
          "Process overview": "进程总览"
          "Work log": "工作记录"
          "Process Monitor": "进程监控器"
nav:
  - Home: README.md
  - Account:
    - Register: 'account/register.md'
    - AdminReg: 'account/adminreg.md'
  - Template: 
    - Concept: "template/concept.md"
    - Template Browser: "template/explorer.md"
    - Design Template: "template/design.md"
    - Role Definition: "designer/pds.md"
  - Designer: "template/designer.md"
  - Process: 
    - Start a process: "process/start.md"
    - Process explorer: "process/explorer.md"
    - Process overview: "process/overview.md"
    - Work log: "process/worklog.md"
    - Process Monitor: "process/monitor.md"
  - Work: 
    - Worklist : "work/worklist.md"
    - Work Page : "work/workpage.md"
  - Setting:
    - Personal: 'about.md'
    - Org: 'about.md'
    - Orgchart: 'about.md'
    - List: 'about.md'
    - Invitation: 'account/invitation.md'
    - Join Approval: 'account/join.md'
  - For Developers:
    - API: 'api.md'
    - SDK: 'sdk.md'
    - Integration: 'integration.md'
  - Q&A: "qa.md"
  - About: about.md

